### ISSUE TITLE
chapter_four code have error

### ISSUE THREAD

**Issue by kunlong-luo** [PacktPublishing/Modern-Android-13-Development-Cookbook#6]
In chapter_four i can't find BottomNavigation and BottomNavigationItem function.

![image](https://github.com/PacktPublishing/Modern-Android-13-Development-Cookbook/assets/40263163/5ec9de56-d510-4f42-973a-59f62790e385)

**Comment by Madonahs** [comment]
Looks like an IDE or import issue, maybe they can try importing right
library. Ask them what IDE they're using.

**Comment by kunlong-luo** [comment]
ok, thanks
